version: '3.8'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prince
      - MONGO_INITDB_ROOT_PASSWORD=prince
      - MONGO_INITDB_DATABASE=jal-shakti
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
volumes:
  db_data:
